#   _                   _                      _
#  | |_ _ __ __ ___   _(_)___  _   _ _ __ ___ | |
#  | __| '__/ _` \ \ / / / __|| | | | '_ ` _ \| |
#  | |_| | | (_| |\ V /| \__ \| |_| | | | | | | |
# (_)__|_|  \__,_| \_/ |_|___(_)__, |_| |_| |_|_|
#                              |___/
#

language: c

os:
  - centos 6
  - ubuntu 15

install:
  - bash -c "$(curl -L raw.githubusercontent.com/april418/dotfiles/master/etc/install)"

script:
  - make test

sudo: required

