#!/bin/bash

#  _                     _ _
# | |__  _   _ _ __   __| | | ___ _ __
# | '_ \| | | | '_ \ / _` | |/ _ \ '__|
# | |_) | |_| | | | | (_| | |  __/ |
# |_.__/ \__,_|_| |_|\__,_|_|\___|_|
#
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

gem install bundler

e_indent 4 "$(e_done "Install")"
e_newline

