#!/bin/bash

#      _ _               _                                _            _             _
#   __| (_)_ __ ___ ___ | | ___  _ __ ___       ___  ___ | | __ _ _ __(_)_______  __| |
#  / _` | | '__/ __/ _ \| |/ _ \| '__/ __|_____/ __|/ _ \| |/ _` | '__| |_  / _ \/ _` |
# | (_| | | | | (_| (_) | | (_) | |  \__ \_____\__ \ (_) | | (_| | |  | |/ /  __/ (_| |
#  \__,_|_|_|  \___\___/|_|\___/|_|  |___/     |___/\___/|_|\__,_|_|  |_/___\___|\__,_|
#
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark > $HOME/.dircolors

e_indent 4 "$(e_done "Install")"
e_newline

