#!/bin/bash

#        _ _
#   __ _(_) |_
#  / _` | | __|
# | (_| | | |_
#  \__, |_|\__|
#  |___/
#

source "$DOTPATH/etc/core"

e_newline
e_header "Install $(basename $0)" | e_indent

package install git

e_newline
e_done "Install" | e_indent

