#!/bin/bash

#        _ _
#   __ _(_) |_
#  / _` | | __|
# | (_| | | |_
#  \__, |_|\__|
#  |___/
#

source "$DOTPATH/etc/core"

e_newline
e_indent 4 $(e_header "Install $(basename $0)")

package install git

e_newline
e_indent 4 $(e_done "Install")

