#!/bin/bash

#        _ _
#   __ _(_) |_
#  / _` | | __|
# | (_| | | |_
#  \__, |_|\__|
#  |___/
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

package install git

e_indent 4 "$(e_done "Install")"
e_newline

