#!/bin/bash

#        _ _                                  _      _   _
#   __ _(_) |_       ___ ___  _ __ ___  _ __ | | ___| |_(_) ___  _ __
#  / _` | | __|____ / __/ _ \| '_ ` _ \| '_ \| |/ _ \ __| |/ _ \| '_ \
# | (_| | | ||_____| (_| (_) | | | | | | |_) | |  __/ |_| | (_) | | | |
#  \__, |_|\__|     \___\___/|_| |_| |_| .__/|_|\___|\__|_|\___/|_| |_|
#  |___/                               |_|
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

curl -L https://github.com/git/git/raw/master/contrib/completion/git-completion.bash > ~/.git-completion.bash

e_indent 4 "$(e_done "Install")"
e_newline

