#!/bin/bash

#                   _                     _ _
#  _ __   ___  ___ | |__  _   _ _ __   __| | | ___
# | '_ \ / _ \/ _ \| '_ \| | | | '_ \ / _` | |/ _ \
# | | | |  __/ (_) | |_) | |_| | | | | (_| | |  __/
# |_| |_|\___|\___/|_.__/ \__,_|_| |_|\__,_|_|\___|
#
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

bash -c "$(curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh)"

e_indent 4 "$(e_done "Install")"
e_newline

