#!/bin/bash

#            _
#  _____ __ | |_   _  __ _
# |_  / '_ \| | | | |/ _` |
#  / /| |_) | | |_| | (_| |
# /___| .__/|_|\__,_|\__, |
#     |_|            |___/
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

#if is_exists curl; then
#  curl -sL zplug.sh/installer | zsh
#else
  export ZPLUG_HOME="$HOME/.zplug"
  git clone https://github.com/zplug/zplug $ZPLUG_HOME
#fi

e_indent 4 "$(e_done "Install")"
e_newline

