#!/bin/bash

#          _
#  _______| |__
# |_  / __| '_ \
#  / /\__ \ | | |
# /___|___/_| |_|
#
#

source "$DOTPATH/etc/core"

e_newline
e_indent 4 $(e_header "Install $(basename $0)")

package install zsh

e_newline
e_indent 4 $(e_done "Install")

