#!/bin/bash

#          _
#  _______| |__
# |_  / __| '_ \
#  / /\__ \ | | |
# /___|___/_| |_|
#
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

package install zsh

e_indent 4 "$(e_done "Install")"
e_newline

