#!/bin/bash

#      _ _
#   __| | | ___ __ ___  ___
#  / _` | |/ / '_ ` _ \/ __|
# | (_| |   <| | | | | \__ \
#  \__,_|_|\_\_| |_| |_|___/
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

sudo rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
package update
package install dkms

e_indent 4 "$(e_done "Install")"
e_newline

