#!/bin/bash

#                                   _
# __   ____ _  __ _ _ __ __ _ _ __ | |_
# \ \ / / _` |/ _` | '__/ _` | '_ \| __|
#  \ V / (_| | (_| | | | (_| | | | | |_
#   \_/ \__,_|\__, |_|  \__,_|_| |_|\__|
#             |___/
#

VAGRANT_VERSION=2.0.0

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

# install virtualbox
sudo sed -i -e '$ a deb http://download.virtualbox.org/virtualbox/debian raring contrib' /etc/apt/sources.list
sudo wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get  -y install virtualbox
sudo usermod -a -G vboxusers "$(echo $USER)"

# install vagrant
wget "https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_$(uname -m).deb" -P $HOME
sudo dpkg --install "$HOME/vagrant_${VAGRANT_VERSION}_$(uname -m).deb"
rm -f "$HOME/vagrant_${VAGRANT_VERSION}_$(uname -m).deb"

e_indent 4 "$(e_done "Install")"
e_newline

