#!/bin/bash

#  _       _ _   _       _ _
# (_)_ __ (_) |_(_) __ _| (_)_______
# | | '_ \| | __| |/ _` | | |_  / _ \
# | | | | | | |_| | (_| | | |/ /  __/
# |_|_| |_|_|\__|_|\__,_|_|_/___\___|
#

# include core script
include_core() {
  source "$DOTPATH/etc/core"
}

keep_sudo() {
  # Ask for the administrator password upfront
  sudo -v

  # Keep-alive: update existing `sudo` time stamp
  #             until this script has finished
  while true
  do
    sudo -n true
    sleep 60;
    kill -0 "$$" || exit
  done 2>/dev/null &
}

confirm_dotpath_exist() {
  if [ -z "$DOTPATH" ]; then
    echo '$DOTPATH: not set' >&2
    exit 1
  fi
}

initialize() {
  for i in "$DOTPATH/etc/init/$(detect_os | head -n1)/*.sh"
  do
    if [ -f "$i" ]; then
      log_info "$(e_arrow "$(basename "$i")")"
      if [ "${DEBUG:-}" != 1 ]; then
        bash "$i"
      fi
    else
      continue
    fi
  done
}



# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu
include_core
confirm_dotpath_exist
keep_sudo
initialize
log_pass "$0: Finish!!" | sed "s $DOTPATH \$DOTPATH g"

