#!/bin/bash

#  _       _ _   _       _ _
# (_)_ __ (_) |_(_) __ _| (_)_______
# | | '_ \| | __| |/ _` | | |_  / _ \
# | | | | | | |_| | (_| | | |/ /  __/
# |_|_| |_|_|\__|_|\__,_|_|_/___\___|
#
#

# include core script
include_core() {
  source "$DOTPATH/etc/core"
}

keep_sudo() {
  # Ask for the administrator password upfront
  sudo -v

  # Keep-alive: update existing `sudo` time stamp
  #             until this script has finished
  while true; do
    sudo -n true
    sleep 60;
    kill -0 "$$" || exit
  done 2>/dev/null &
}

confirm_dotpath_exist() {
  if [ -z "$DOTPATH" ]; then
    e_error '$DOTPATH: not set'
    exit 1
  fi
}

initialize() {
  init_path="$DOTPATH/etc/init/$(detect_os | head -n1)"
  for p in $(ls $init_path); do
    if [ -f "$init_path/$p" ]; then
      e_indent 2 "$(e_arrow $p)"
      bash "$init_path/$p"
    fi
  done
}



# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu
include_core
confirm_dotpath_exist
keep_sudo
initialize
e_indent 2 "$(e_done "$(basename $0): Finish!!")"

