#!/bin/bash

#              _
#   __ _ _ __ | |_       ___ _   _  __ _
#  / _` | '_ \| __|____ / __| | | |/ _` |
# | (_| | |_) | ||_____| (__| |_| | (_| |
#  \__,_| .__/ \__|     \___|\__, |\__, |
#       |_|                  |___/ |___/
#

source "$DOTPATH/etc/core"

e_indent 4 "$(e_header "Install $(basename $0 | sed -e 's/[0-9_]//g')")"

curl https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg > ~/bin/apt-cyg
chmod 755 ~/bin/apt-cyg

e_indent 4 "$(e_done "Install")"
e_newline

